bind = "0.0.0.0:25565"
motd = ""
show-max-players = 0
online-mode = false
player-info-forwarding-mode = "NONE"
announce-forge = false
force-key-authentication = false

[servers]
kaboom = "kaboom:25565"

try = ["kaboom"]

[forced-hosts]

[advanced]
compression-threshold = 256
compression-level = -1
login-ratelimit = 5000
connection-timeout = 5000
read-timeout = 30000
proxy-protocol = false

[query]
enabled = false

[metrics]
enabled = false
id = "00000000-0000-0000-0000-000000000000"
log-failure = false
